apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: demo-liveness
  labels:
    name: app
    project: A
  annotations:
    created-by: team-A
spec:
  containers:
    - image: esmaeil157/demo-app:unhealthy
      name: app
      ports:
        - containerPort: 8080
          protocol: TCP
          name: http
      livenessProbe:
        httpGet:
          # scheme: HTTP
          # host: test.com
          port: http
          path: /
          # httpHeaders:
            # - name: Host
            #   value: test.com
            # - name: User-Agent
            #   value: kube-probe/1.25
            # - name: Accept
            #   value: "*/*"
        # initialDelaySeconds: 30
        # periodSeconds: 10
        # timeoutSeconds: 5
        # successThreshold: 1
        # failureThreshold: 3
        # Override pod-level terminationGracePeriodSeconds
      # pod-level
    # terminationGracePeriodSeconds" 3600