apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: psc-ns
spec:
  storageClassName: test-sc # this name of storage class name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi