apiVersion: v1
kind: ReplicationController
metadata:
  name: app
  namespace: replica-set
  labels:
    name: app
    project: A
  annotations:
    created-by: team-A
spec:
  replicas: 3
  selector:
    app: app
    project: A
  template:
    metadata:
      name: app
      labels:
        app: app
        project: A
    spec:
      containers:
      - name: app
        image: esmaeil157/demo-app:v1.0.0
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        livenessProbe:
          httpGet:
            port: http
            path: /
        
            
