apiVersion: v1
kind: ReplicationController
metadata:
  name: app
  namespace: replica-ns
  labels:
    name: app
    project: A
  annotations:
    created-by: team-A
spec:
  replicas: 3
  selector:
    name: app
    project: A
  template:
    metadata:
      name: app
      labels:
        name: app
        project: A
    spec:
      containers:
      - image: esmaeil157/demo-app:v1.0.0
        name: app
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        livenessProbe:
          httpGet:
            port: http
            path: /



# metadata:
#   name: myapp
# spec:
#   replicas: <Replicas>
#   selector:
#     app: myapp
#   template:
#     metadata:
#       name: myapp
#       labels:
#         app: myapp
#     spec:
#       containers:
#         - name: myapp
#           image: <Image>
#           ports:
#             - containerPort: <Port>
